TEAMS = {
    "49ers" : "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=SF",
    "Bears": "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=CHI",
    "Bengals": "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=CIN",
    "Bills" : "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=BUF",
    "Broncos" : "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=DEN",
    "Browns" : "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=CLE",
    "Bucs" : "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=TB",
    "Cardinals" : "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=ARI",
    "Chargers" : "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=LAC",
    "Chiefs" : "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=KC",
    "Colts" : "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=IND",
    "Commanders" : "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=WAS",
    "Cowboys" : "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=DAL",
    "Dolphins" : "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=MIA",
    "Eagles" : "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=PHI",
    "Falcons" : "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=ATL",
    "Giants" : "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=NYG",
    "Jaguars" : "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=JAX",
    "Jets" : "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=NYJ",
    "Lions" : "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=DET",
    "Packers" : "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=GB",
    "Panthers" : "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=CAR",
    "Patriots" : "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=NE",
    "Raiders" : "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=LV",
    "Rams" : "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=LAR",
    "Ravens" : "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=BAL",
    "Saints" : "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=NO",
    "Seahawks" : "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=SEA",
    "Steelers" : "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=PIT",
    "Texans" : "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=HOU",
    "Titans" : "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=TEN",
    "Vikings" : "https://neonsportz.com/leagues/2MD/players?page_size=50&team__abbrName=MIN",
}